### ISSUE TITLE
Umbrella Issue for "Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by SaraVieira** [codesandbox/codesandbox-client#5406]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Sometimes when using codesandbox the page will just break with the error:

```
TypeError: Cannot convert undefined or null to object
```

This error only happens in Chrome-based browsers and it comes from the sentry SDK:
![CleanShot 2021-01-27 at 14 36 58](https://user-images.githubusercontent.com/1051509/105998656-303f5e00-60ad-11eb-8bce-fd511267e959.png) 

https://sentry.io/organizations/codesandbox/issues/1730507122/?project=2071895&query=%22Cannot+convert+undefined+or+null+to+object+%22&statsPeriod=90d

I created a related issue in the sentry javascript library

## How has this issue affected you? What are you trying to accomplish?

Not me but people's codesandbox breaks out of nowhere

### To Reproduce

No one has a clue

### Link to issues:

#5420 
 #5017
 #4992
 #5346
 #5326

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | any
| Browser          | Chromium 	
| Operating System | any

**Comment by kamilogorek** [comment]
Hey there, Sentry dev here. 

> This error only happens in Chrome-based browsers and it comes from the sentry SDK:

When you open the last frame of the stack trace, you can see this note:
![image](https://user-images.githubusercontent.com/1523305/106008305-71d50680-60b7-11eb-910b-f1f8d13ff4d5.png)

The reason why it looks like it comes from Sentry, is that we are wrapping some APIs (in this case requestAnimationFrame), to extract function name and capture arguments to the function call. The code that's throwing however, is the original function that has been wrapped. You can find parsed arguments in the `Additional Data` section, and it may help finding the cause of the issue:
![image](https://user-images.githubusercontent.com/1523305/106008675-d6906100-60b7-11eb-8efc-4fa5df2c7e36.png)

Let me know if I can help you in any way, cheers! :)

**Comment by SaraVieira** [comment]
Hey!

That does make sense, I do still get sentry code in the one linked above tho :(
![CleanShot 2021-01-27 at 16 12 43](https://user-images.githubusercontent.com/1051509/106011269-97174400-60ba-11eb-9a29-28c7004f2fcf.png)

**Comment by SaraVieira** [comment]
This also may be just me not knowing how to use sentry be warned 

Also sorry for saying "This comes from sentry", I couldn't really find anything that pointed in another direction

**Comment by kamilogorek** [comment]
You could try to disable all timers instrumentation and see whether new events that come up will include any more information or less obfuscated stacktrace. Let me know if you decide to give it a shot and you capture any similar events.

```js
import * as Sentry from '@sentry/browser';

Sentry.init({
  // ...
  integrations: [new Sentry.Integrations.TryCatch({
    setTimeout: false,
    setInterval: false,
    requestAnimationFrame: false,
  })]
});
```

**Comment by SaraVieira** [comment]
Thank you! Made a PR, probably will get merged on Monday and I will keep a track on the errors to see if we get more of the same one.

Thank you!

**Comment by kamilogorek** [comment]
btw. I see that you have browsers extensions filtered in the configuration. You can do that straight in the UI in project/org settings :)

![image](https://user-images.githubusercontent.com/1523305/106318028-76dcb600-626f-11eb-93e6-8a7c44c89652.png)

**Comment by SaraVieira** [comment]
Oh nice! Removed it from the code and will ask ives to add that as I don't have permissions

Thank you!
